name: foody_licious_admin_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #firebase
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2

  #local storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.4

  #state management
  bloc: ^8.1.2
  flutter_bloc: ^8.0.1
  get_it: ^7.6.0

  http: ^1.5.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pinput: ^5.0.1
  smart_auth: ^3.2.0
  carousel_slider: ^5.0.0
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.2
  open_mail_app_plus: ^0.0.2
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  image_picker: ^1.1.2

  #ui
  flutter_screenutil: ^5.9.3
  google_fonts: ^4.0.4
  persistent_bottom_nav_bar: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # test
  mocktail: ^0.3.0
  bloc_test: ^9.1.4  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/utils/